name: Deploy via ftp
on:
  push:
    branches: ['master']
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn generate

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './dist/'
          server-dir: './www.gdpay8.com/test/'
          port: 21212
    # - name: send default message
    #   uses: appleboy/telegram-action@master
    #   with:
    #     to: ${{ secrets.TELEGRAM_TO }}
    #     token: ${{ secrets.TELEGRAM_TOKEN }}
    #     message: |
    #         亲爱的各位领导:
    #         小的已经将网页资料部属完毕
    #         请移驾到 https://www.xn--x9qy6jot9btfq.com/ 查看结果
